name: Auto Release and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag-exists
        run: |
          if git rev-parse "v${{ steps.package-version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.tag-exists.outputs.exists == 'false'
        run: npm ci

      - name: Build
        if: steps.tag-exists.outputs.exists == 'false'
        run: npm run build

      - name: Publish to NPM
        if: steps.tag-exists.outputs.exists == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create and push tag
        if: steps.tag-exists.outputs.exists == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag v${{ steps.package-version.outputs.version }}
          git push origin v${{ steps.package-version.outputs.version }}

      - name: Create GitHub Release
        if: steps.tag-exists.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release created notification
        if: steps.tag-exists.outputs.exists == 'false'
        run: echo "🚀 Successfully published v${{ steps.package-version.outputs.version }} to NPM and created GitHub release"

      - name: Already released notification
        if: steps.tag-exists.outputs.exists == 'true'
        run: echo "ℹ️ Version v${{ steps.package-version.outputs.version }} already released, skipping"